const items = [
    {title:"*keep smiling smiles*", tag: ["Monochrome"], img:"/Images/mwangi_kirungoh_1710512906894.jpeg"},
    {title:"*keep smiling smiles*", tag: ["Graduations"], img:"/Images/graduate.jpg"},
    {title:"keep smiling smiles", tag: ["Baby-Showers"], img:"/Images/mbucha.jpg"},
    {title:"keep smiling smiles", tag: ["Mixin"], img:"/Images/viuu.jpg"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/wedding.jpg"},
    {title:"keep smiling smiles", tag: ["Portraits"], img:"/Images/Landimbisha.jpg"},
    {title:"keep smiling smiles", tag: ["Monochrome"], img:"/Images/Mie.jpg"},
    {title:"keep smiling smiles", tag: ["Monochrome"], img:"/Images/Mnisa.jpg"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/wedding.jpg"},
    {title:"keep smiling smiles", tag: ["Mixin"], img:"/Images/viuu.jpg"},
    {title:"keep smiling smiles", tag: ["Graduations"], img:"/Images/graduation.jpg"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/mbucha.JPG"},
    //{title:"keep smiling smiles", tag: ["Portraits"], img:"/Images/Kendrick Lamar.jpg"},
];