const items = [
    {title:"*keep smiling smiles*", tag: ["Monochrome"], img:"/Images/mwangi_kirungoh_1710512906894.webp"},
    {title:"*keep smiling smiles*", tag: ["Graduations"], img:"/Images/graduate.webp"},
    {title:"keep smiling smiles", tag: ["Baby-Showers"], img:"/Images/mbucha.webp"},
    {title:"keep smiling smiles", tag: ["Flora'n'Fauna"], img:"/Images/wildife3cat.webp"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/wedding.webp"},
    {title:"keep smiling smiles", tag: ["Portraits"], img:"/Images/Landimbisha.webp"},
    {title:"keep smiling smiles", tag: ["All"], img:"Images/radioneiba.webp"},
    {title:"keep smiling smiles", tag: ["Monochrome"], img:"/Images/Mnisa.webp"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/wedding.webp"},
    {title:"keep smiling smiles", tag: ["Flora'n'Fauna"], img:"/Images/wildlife1zebra.webp"},
    {title:"keep smiling smiles", tag: ["Graduations"], img:"/Images/graduation.webp"},
    {title:"keep smiling smiles", tag: ["Weddings"], img:"/Images/mbucha.webp"},
    {title:"keep smiling smiles", tag: ["Flora'n'Fauna"], img:"Images/wildlife2cat.webp"},
    //{title:"keep smiling smiles", tag: ["Portraits"], img:"/Images/Kendrick Lamar.jpg"},
];